workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - manual_code_signing
      vars:
        APP_ID: "uk.asherlewis.theforge"
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Initialize Keychain
        script: keychain initialize
      - name: Decode Key (Mac Safe Mode)
        script: |
          # Use -D for macOS decoding and write to a temporary file
          echo "$IOS_AUTH_KEY" | base64 -D > /tmp/apikey.p8
          
          # Verify the file looks correct (First line should be -----BEGIN...)
          if grep -q "BEGIN PRIVATE KEY" /tmp/apikey.p8; then
            echo "✅ Key decoded successfully!"
          else
            echo "❌ Key decode failed. Trying Linux mode..."
            echo "$IOS_AUTH_KEY" | base64 --decode > /tmp/apikey.p8
          fi

      - name: Set up code signing settings
        script: |
          app-store-connect fetch-signing-files "$APP_ID" \
            --type IOS_APP_STORE \
            --create \
            --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" \
            --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" \
            --private-key @/tmp/apikey.p8
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Build IPA
        script: >-
          xcode-project build-ipa
          --workspace "ios/App/App.xcworkspace"
          --scheme "App"
          --config Release
    publishing:
      app_store_connect:
        # We point to the file path now, as the variable contains Base64 (which Apple can't read directly)
        api_key: @/tmp/apikey.p8
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
