workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      groups:
        - manual_code_signing
      vars:
        APP_ID: "uk.asherlewis.theforge"
      xcode: latest
      node: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
      - name: Initialize Keychain
        script: keychain initialize
      - name: Set up code signing settings
        script: |
          app-store-connect fetch-signing-files "$APP_ID" --type IOS_APP_STORE --create --issuer-id "$APP_STORE_CONNECT_ISSUER_ID" --key-id "$APP_STORE_CONNECT_KEY_IDENTIFIER" --private-key "$APP_STORE_CONNECT_PRIVATE_KEY"
      - name: Add certs to keychain
        script: keychain add-certificates
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App" --config Release
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true